use serde::{Deserialize, Deserializer, Serialize};
use std::fmt;
use std::hash::{Hash, Hasher};

/// Sonar synthetic song ids carry the top bit so callers can distinguish
/// third-party search results from NCM songs.
pub const SONAR_ID_FLAG: u64 = 1 << 63;

/// Build a stable synthetic id for a sonar song. Deterministic across runs so
/// cache entries and saved sessions survive restarts.
pub fn make_song_id(source: SonarSource, source_id: &str) -> u64 {
    let mut hasher = std::collections::hash_map::DefaultHasher::new();
    format!("{source}:{source_id}").hash(&mut hasher);
    hasher.finish() | SONAR_ID_FLAG
}

/// Whether a song id belongs to a sonar search result rather than NCM.
pub fn is_sonar_song_id(id: u64) -> bool {
    id & SONAR_ID_FLAG != 0
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct Song {
    /// Synthetic id generated by [`make_song_id`]; the app keys registries and
    /// cache entries on it.
    pub id: u64,
    /// Provider-native id (kugou hash / kuwo rid / bvid / youtube video id),
    /// used when resolving a play URL through the provider.
    pub source_id: String,
    pub name: String,
    pub singer: String,
    pub album: String,
    pub duration: u64,
    pub source: SonarSource,
    /// Cover image URL (empty when the provider has none).
    pub pic_url: String,
    /// Provider-specific fields required to resolve a play URL.
    pub meta: SongMeta,
}

/// Kugou stores its candidate hashes and album id outside the common fields;
/// other providers leave this empty.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
pub struct SongMeta {
    /// Kugou high-quality (320kbps) hash.
    pub high_hash: Option<String>,
    /// Kugou lossless (sq) hash.
    pub lossless_hash: Option<String>,
    /// Kugou album id, echoed when requesting the track URL.
    pub album_id: String,
}

/// Backward-compatible deserialization: the on-disk cache index may still hold
/// songs written in the legacy shape (String `id`, `artists`, `album`,
/// `quality`, `raw_data`). Map those onto the current fields.
impl<'de> Deserialize<'de> for Song {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: Deserializer<'de>,
    {
        #[derive(Deserialize)]
        #[serde(untagged)]
        enum Id {
            New(u64),
            Old(String),
        }

        #[derive(Deserialize)]
        struct RawArtist {
            #[serde(default)]
            name: String,
        }

        #[derive(Deserialize)]
        #[serde(untagged)]
        enum RawAlbum {
            Flat(String),
            Obj {
                #[serde(default)]
                name: String,
            },
        }

        fn album_name(album: &Option<RawAlbum>) -> String {
            match album {
                Some(RawAlbum::Flat(s)) => s.clone(),
                Some(RawAlbum::Obj { name }) => name.clone(),
                None => String::new(),
            }
        }

        #[derive(Deserialize)]
        struct Raw {
            id: Option<Id>,
            #[serde(default)]
            source_id: Option<String>,
            #[serde(default)]
            name: Option<String>,
            #[serde(default)]
            singer: Option<String>,
            #[serde(default)]
            artists: Vec<RawArtist>,
            #[serde(default)]
            album: Option<RawAlbum>,
            #[serde(default)]
            duration: Option<u64>,
            #[serde(default)]
            source: Option<SonarSource>,
            #[serde(default)]
            pic_url: Option<String>,
            #[serde(default)]
            meta: Option<SongMeta>,
        }

        let raw = Raw::deserialize(deserializer)?;

        match raw.id {
            // Current shape.
            Some(Id::New(id)) => Ok(Song {
                id,
                source_id: raw.source_id.unwrap_or_default(),
                name: raw.name.unwrap_or_default(),
                singer: raw.singer.unwrap_or_default(),
                album: album_name(&raw.album),
                duration: raw.duration.unwrap_or(0),
                source: raw.source.unwrap_or(SonarSource::Kugou),
                pic_url: raw.pic_url.unwrap_or_default(),
                meta: raw.meta.unwrap_or_default(),
            }),
            // Legacy shape: `id` is the provider-native string, singer was
            // spread over `artists`, and the synthetic id must be rebuilt.
            Some(Id::Old(legacy_id)) => {
                let source = raw.source.unwrap_or(SonarSource::Kugou);
                let source_id = raw.source_id.unwrap_or(legacy_id);
                Ok(Song {
                    id: make_song_id(source, &source_id),
                    source_id,
                    name: raw.name.unwrap_or_default(),
                    singer: raw.singer.unwrap_or_else(|| {
                        raw.artists
                            .first()
                            .map(|a| a.name.clone())
                            .unwrap_or_default()
                    }),
                    album: album_name(&raw.album),
                    duration: raw.duration.unwrap_or(0),
                    source,
                    pic_url: raw.pic_url.unwrap_or_default(),
                    meta: raw.meta.unwrap_or_default(),
                })
            }
            None => Err(serde::de::Error::custom("song is missing an id")),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum SonarSource {
    Kugou,
    Kuwo,
    BiliVideo,
    Youtube,
}

impl fmt::Display for SonarSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SonarSource::Kugou => write!(f, "kugou"),
            SonarSource::Kuwo => write!(f, "kuwo"),
            SonarSource::BiliVideo => write!(f, "bilivideo"),
            SonarSource::Youtube => write!(f, "youtube"),
        }
    }
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum Quality {
    Standard,
    High,
    Lossless,
}

impl fmt::Display for Quality {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Quality::Standard => write!(f, "standard"),
            Quality::High => write!(f, "high"),
            Quality::Lossless => write!(f, "lossless"),
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SearchQuery {
    pub keyword: String,
    pub page: Option<u32>,
    pub page_size: Option<u32>,
    /// Optional expected duration in milliseconds, used as a scoring hint.
    pub duration: Option<u64>,
}

impl SearchQuery {
    pub fn new(keyword: impl Into<String>) -> Self {
        Self {
            keyword: keyword.into(),
            page: Some(1),
            page_size: Some(30),
            duration: None,
        }
    }

    pub fn with_page(mut self, page: u32) -> Self {
        self.page = Some(page);
        self
    }

    pub fn with_page_size(mut self, page_size: u32) -> Self {
        self.page_size = Some(page_size);
        self
    }

    pub fn with_duration(mut self, duration_ms: u64) -> Self {
        self.duration = Some(duration_ms);
        self
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SearchResult {
    pub songs: Vec<Song>,
    pub source: SonarSource,
    pub query: SearchQuery,
    pub total: Option<u32>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlayUrlResult {
    pub url: String,
    pub quality: Quality,
    pub size: Option<u64>,
    pub bitrate: Option<u32>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flags_sonar_ids() {
        let id = make_song_id(SonarSource::Kuwo, "60478382");
        assert!(is_sonar_song_id(id));
    }

    #[test]
    fn does_not_flag_ncm_ids() {
        assert!(!is_sonar_song_id(186150));
        assert!(!is_sonar_song_id(!SONAR_ID_FLAG));
    }

    #[test]
    fn ids_are_stable() {
        let a = make_song_id(SonarSource::Kugou, "abc123");
        let b = make_song_id(SonarSource::Kugou, "abc123");
        assert_eq!(a, b);
        assert_ne!(a, make_song_id(SonarSource::Kuwo, "abc123"));
        assert_ne!(a, make_song_id(SonarSource::Kugou, "abc124"));
    }

    #[test]
    fn round_trips_current_shape() {
        let song = Song {
            id: make_song_id(SonarSource::Kuwo, "123"),
            source_id: "123".to_string(),
            name: "晴天".to_string(),
            singer: "周杰伦".to_string(),
            album: "叶惠美".to_string(),
            duration: 269000,
            source: SonarSource::Kuwo,
            pic_url: "http://pic".to_string(),
            meta: SongMeta::default(),
        };
        let json = serde_json::to_string(&song).unwrap();
        let back: Song = serde_json::from_str(&json).unwrap();
        assert_eq!(song, back);
    }

    #[test]
    fn maps_legacy_shape() {
        let legacy = serde_json::json!({
            "id": "hash123",
            "name": "晴天",
            "artists": [{"id": "", "name": "周杰伦"}],
            "album": {"id": "", "name": "叶惠美"},
            "duration": 269000,
            "source": "Kugou",
            "quality": "High",
            "url": null,
            "pic_url": "",
            "raw_data": {"sqhash": "sq", "320hash": "hq"}
        });
        let song: Song = serde_json::from_value(legacy).unwrap();
        assert_eq!(song.source_id, "hash123");
        assert_eq!(song.singer, "周杰伦");
        assert_eq!(song.album, "叶惠美");
        assert_eq!(song.source, SonarSource::Kugou);
        assert!(is_sonar_song_id(song.id));
        assert_eq!(song.id, make_song_id(SonarSource::Kugou, "hash123"));
    }
}
